import type { Metadata } from "next";
import "./globals.css";

import { Nobile } from "next/font/google";
const nobile = Nobile({ subsets: ["latin"], weight: ["400", "500", "700"] })


import { Jost } from "next/font/google";
const jost = Jost({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '700', '900'], style: ['normal', 'italic'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} ${nobile.className}`}>{children}</body>
    </html>
  );
}
